server:
  port: 8080

logging:
  level:
    root: info

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      resourceserver:
        jwt:
          #The jwk-set-uri property contains the public key that the server can use to verify the Token’s signature to make sure the data has not been modified
          #在authorization server 配置@bean中可以输出,或者从jks中写代码输出. https://connect2id.com/products/nimbus-jose-jwt/examples/jwk-generation#rsa
          jwk-set-uri: http://localhost:9000/oauth2/jwks
      client:
        registration:
          login-client-authorization-code:
            provider: peacerise
            client-id: login-client
            client-secret: login-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/peacerise/sitelogin/authorized"
            scope: site-login.read
            client-name: login-client-authorization-code
          login-client-client-credentials:
            provider: peacerise
            client-id: login-client
            client-secret: login-secret
            authorization-grant-type: client_credentials
            scope: site-login.read
            client-name: login-client-client-credentials
        provider:
          peacerise:
            issuer-uri: http://localhost:9000
